"""empty message

Revision ID: 025db43e0a93
Revises: 50baf778c3ab
Create Date: 2018-05-18 11:06:56.700514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '025db43e0a93'
down_revision = '50baf778c3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_seen_list',
    sa.Column('myseenlist_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('tv', sa.Text(), nullable=True),
    sa.Column('theater', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.director_id'], ),
    sa.PrimaryKeyConstraint('myseenlist_id'),
    sa.UniqueConstraint('myseenlist_id')
    )
    op.drop_index('myseenlist_id', table_name='my_seenlist')
    op.drop_table('my_seenlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_seenlist',
    sa.Column('myseenlist_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('director_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tv', mysql.TEXT(), nullable=True),
    sa.Column('theater', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.director_id'], name='my_seenlist_ibfk_1'),
    sa.PrimaryKeyConstraint('myseenlist_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('myseenlist_id', 'my_seenlist', ['myseenlist_id'], unique=True)
    op.drop_table('my_seen_list')
    # ### end Alembic commands ###
