"""empty message

Revision ID: 299a24c4fd38
Revises: 025db43e0a93
Create Date: 2018-05-23 10:16:57.429922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '299a24c4fd38'
down_revision = '025db43e0a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=255),
               nullable=False)
    # ### end Alembic commands ###
