"""empty message

Revision ID: d98f35d60b2c
Revises: 299a24c4fd38
Create Date: 2018-10-17 09:39:52.898431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd98f35d60b2c'
down_revision = '299a24c4fd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=255), nullable=True),
    sa.Column('season_episodes', sa.String(length=255), nullable=True),
    sa.Column('poster', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('serie_id')
    )
    op.create_index(op.f('ix_serie_year'), 'serie', ['year'], unique=False)
    op.alter_column('director', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=255),
               nullable=True,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('director', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_spanish2_ci', length=255),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('ix_serie_year'), table_name='serie')
    op.drop_table('serie')
    # ### end Alembic commands ###
